"""add recommendations

Revision ID: 77de89b3aef2
Revises: 3ed1c63782ed
Create Date: 2026-08-17 00:26:57.126352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '77de89b3aef2'
down_revision: Union[str, Sequence[str], None] = '3ed1c63782ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendations',
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    # content_type 은 contents 가 이미 만들어뒀다. create_type=False 가 없으면 CREATE TYPE 이 중복된다
    sa.Column('type', postgresql.ENUM(name='content_type', create_type=False), nullable=False),
    sa.Column('rank', sa.SmallInteger(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('reason_source', sa.Enum('LLM', 'TEMPLATE', name='reason_source'), nullable=False),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('batch_id', 'content_id')
    )
    op.create_index('ix_recommendations_batch_type_rank', 'recommendations', ['batch_id', 'type', 'rank'], unique=False)
    op.add_column('users', sa.Column('current_rec_batch_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_rec_batch_id')
    op.drop_index('ix_recommendations_batch_type_rank', table_name='recommendations')
    op.drop_table('recommendations')
    # drop_table 은 enum 타입을 안 지운다. 남으면 다시 upgrade 할 때 CREATE TYPE 이 실패한다
    # content_type 은 contents 가 계속 쓰므로 건드리지 않는다
    op.execute("DROP TYPE IF EXISTS reason_source")
    # ### end Alembic commands ###
