"""add liked to user_contents

Revision ID: 8be038804097
Revises: c77780869202
Create Date: 2026-08-14 16:19:27.590319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8be038804097'
down_revision: Union[str, Sequence[str], None] = 'c77780869202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_contents', sa.Column('liked', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_index('ix_user_contents_liked', 'user_contents', ['user_id', 'liked'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_contents_liked', table_name='user_contents')
    op.drop_column('user_contents', 'liked')
    # ### end Alembic commands ###
