"""add contents table

Revision ID: b51e8f1c9a7d
Revises: 
Create Date: 2026-08-09 16:00:57.841175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b51e8f1c9a7d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contents',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('type', sa.Enum('MOVIE', 'BOOK', 'WEBTOON', name='content_type'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('genre', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('creator', sa.String(length=300), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('external_rating', sa.Float(), nullable=True),
    sa.Column('external_rating_count', sa.Integer(), nullable=True),
    sa.Column('content_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding_text', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('embedded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_contents_source_external')
    )
    op.create_index('ix_contents_genre_gin', 'contents', ['genre'], unique=False, postgresql_using='gin')
    op.create_index('ix_contents_type_title', 'contents', ['type', 'title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contents_type_title', table_name='contents')
    op.drop_index('ix_contents_genre_gin', table_name='contents', postgresql_using='gin')
    op.drop_table('contents')
    op.execute("DROP TYPE IF EXISTS content_type")
    # ### end Alembic commands ###
