"""add login lockout

Revision ID: c62aae84f2d4
Revises: 4a524898faf1
Create Date: 2026-08-18 04:34:36.114098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c62aae84f2d4'
down_revision: Union[str, Sequence[str], None] = '4a524898faf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default 가 없으면 기존 행에서 NOT NULL 위반이 난다
    op.add_column(
        'users',
        sa.Column('failed_logins', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column('users', sa.Column('locked_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_logins')
    # ### end Alembic commands ###
