"""add users and user_contents

Revision ID: c77780869202
Revises: cf854f4e77a9
Create Date: 2026-08-13 20:39:31.817745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c77780869202'
down_revision: Union[str, Sequence[str], None] = 'cf854f4e77a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('nickname', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_contents',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('WISH', 'DOING', 'DONE', name='content_status'), nullable=False),
    sa.Column('recommended', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'content_id')
    )
    op.create_index('ix_user_contents_recommended', 'user_contents', ['user_id', 'recommended'], unique=False)
    op.create_index('ix_user_contents_user_updated', 'user_contents', ['user_id', 'updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_contents_user_updated', table_name='user_contents')
    op.drop_index('ix_user_contents_recommended', table_name='user_contents')
    op.drop_table('user_contents')
    op.drop_table('users')
    op.execute('DROP TYPE content_status')
    # ### end Alembic commands ###