"""rename external_rating_count to external_popularity

Revision ID: cf854f4e77a9
Revises: b51e8f1c9a7d
Create Date: 2026-08-10 19:17:25.703017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf854f4e77a9'
down_revision: Union[str, Sequence[str], None] = 'b51e8f1c9a7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contents', 'external_rating_count', new_column_name='external_popularity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contents', 'external_popularity', new_column_name='external_rating_count')
    # ### end Alembic commands ###
