"""replace liked with rating

Revision ID: d36455f5f724
Revises: 8be038804097
Create Date: 2026-08-14 17:27:20.555885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd36455f5f724'
down_revision: Union[str, Sequence[str], None] = '8be038804097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_contents', sa.Column('rating', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_user_contents_liked'), table_name='user_contents')
    op.create_index('ix_user_contents_rating', 'user_contents', ['user_id', 'rating'], unique=False)
    op.drop_column('user_contents', 'liked')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_contents', sa.Column('liked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_index('ix_user_contents_rating', table_name='user_contents')
    op.create_index(op.f('ix_user_contents_liked'), 'user_contents', ['user_id', 'liked'], unique=False)
    op.drop_column('user_contents', 'rating')
    # ### end Alembic commands ###
